### ISSUE TITLE
thanks you for developing this, but I have a laptop with AMD and nVIDIA....

### ISSUE THREAD

**Issue by freebrew** [sultim-t/xash-rt#62]
The game and mod does not detect nVIDIA for DLSS not raytrracing as it is defaulting to use the smaller intergrated AMD iGPU on die instead of the deticated nVIDIA GPU.

Any advice?, I have uploaded the optional rt DLSS files in the appropriate folder and started the game with xash3d.exe executable.

Please advise

**Comment by sultim-t** [comment]
Interesting, the code tries to find the first GPU with ray tracing support. What's that AMD GPU?

**Comment by Summonerrk** [comment]
My Asus laptop with GTX 960m give me a error "xash error host_initerror cant find physical device". Im very upset. Can we it be resolved by any way?

**Comment by freebrew** [comment]
> 
The one integrated inside the Ryzen 9 Mobile 5900HX

![image](https://user-images.githubusercontent.com/13647718/221351087-634e6e38-bce6-4238-a902-ee845cbe0c38.png)

**Comment by freebrew** [comment]
The settings wont give me the DLSS but it is running on the nVIDIA GPU after all....not sure why I dont have access to DLSS, I did upload correctly

![image](https://user-images.githubusercontent.com/13647718/221352191-16a6e2b9-1c85-4766-8b9e-f49af1801adc.png)

![image](https://user-images.githubusercontent.com/13647718/221352224-04938243-c719-49a0-8e19-ac3827e839c4.png)

**Comment by mastan-rus** [comment]
> The settings wont give me the DLSS but it is running on the nVIDIA GPU after all....not sure why I dont have access to DLSS, I did upload correctly

Did you do additional steps for DLSS? 

> Download [nvngx_dlss.dll](https://github.com/NVIDIA/DLSS/blob/main/lib/Windows_x86_64/rel/nvngx_dlss.dll)
> Place it into the rt_bin folder, ensure that it's called nvngx_dlss.dll
> Download [RayTracedGL1-Bundle-DLSS.zip](https://github.com/sultim-t/RayTracedGL1/releases/tag/hl1-dev)
> Replace the original rt_bin/RayTracedGL1.dll with a new one bin/RayTracedGL1.dll from RayTracedGL1-Bundle-DLSS.zip

**Comment by freebrew** [comment]
UPDATE: It is raytracing, as seen from above screen shots on the nVidia card, but the DLSS options are still not availbale in the options menu. And Yes, I did redon the new files in the proper folders.

![image](https://user-images.githubusercontent.com/13647718/221390142-f6ad0468-2a2f-48d2-8d59-6bb0e7344528.png)

![image](https://user-images.githubusercontent.com/13647718/221390175-485d0257-e157-4f52-9141-522c2aa5f9f6.png)

**Comment by mastan-rus** [comment]
Your nvngx_dlss.dll is suspiciously small. Version 3.1.1 linked above should be around 35 MB, older 2.5.1 around 25 MB.
Try downloading here https://www.techpowerup.com/download/nvidia-dlss-dll/

**Comment by freebrew** [comment]
Yup, that worked...Thanks You for your help, very appritiated

**Comment by kunimei** [comment]
thankyou
