### ISSUE TITLE
Lights not rendering

### ISSUE THREAD

**Issue by Plowabletoast88** [sultim-t/xash-rt#80]
Noticed this issue immediately after the tram ride where specific lights across the map were missing. This only applies to a few lights at the starting room and hallway, but the rest of the map is almost entirely pitch black.

![image](https://user-images.githubusercontent.com/65273834/221432858-3bf029a6-4d90-42cc-9b61-9bdfbc459e9d.png)
![image](https://user-images.githubusercontent.com/65273834/221433037-b867b113-302e-4484-ac04-d30420ff082d.png)
![image](https://user-images.githubusercontent.com/65273834/221433069-f4474aa9-6f7c-4a09-9f5a-dca63b13b2e7.png)

**Comment by mastan-rus** [comment]
Similar problem here: https://steamcommunity.com/app/70/discussions/0/3770113150026891784/?ctp=3#c3770113150037294348
They don't explain in detail what happened and how it was solved. Some model was missing? Try doing clean reinstall of the HL without custom mods, models, or configs. Run the game with "-console" argument or via xash3d-console.bat, then open console with ` key and look for errors there.

**Comment by lookingglassed** [comment]
Had the same issue. Try verifying integrity of game files via steam. Delete old saves downloaded from steam cloud. Finally. what worked for me after these 2 steps was re-extracting the RT half-life zip files into the half-life install directory. Once I relaunched the game was fine. Its worth pointing out that verifying the game file integrity alone didn't fix the problem.

**Comment by sultim-t** [comment]
Please, ensure that you have unzipped **hl1-rt-resources.zip**, not just hl1-rt.zip

**Comment by Plowabletoast88** [comment]
Did a clean install with the newest version and so far it seems to have fixed itself
